title: No Sense Generator
description: Documentation for No Sense Generator.
theme: just-the-docs

source: ../../docs
destination: ./_site

url: https://Giovi2004.github.io/NoSenseGenerator

aux_links:
  Template Repository: https://github.com/Giovi2004/NoSenseGenerator
