title: No Sense Generator
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

source: ..
destination: ./_site

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/Giovi2004/NoSenseGenerator


callouts:
  warning:
    title: Warning
    color: red
  success:
    title: Success
    color: green
  note:
    title: Note
    color: purple