@startuml SentenceAnalysis
hide footbox
skinparam sequenceMessageAlign center
title System Sequence Diagram: Sentence Analysis

actor User
participant "NoSense\nSystem" as System

User -> System: input sentence
User -> System: select syntactic tree option
activate System

alt Empty Input
    System --> User: display error "Please enter a sentence to analyze"
else Malformed Sentence
    System --> User: display error "Failed to analyze sentence: invalid structure"
else Valid Input
    note right of System
      Internal steps:
      1. Save input sentence
      2. Validate sentence structure (via Google API)
      3. Extract nouns, verbs, adjectives
    end note
    System --> User: display extracted terms\n(nouns, verbs, adjectives)

    alt Syntactic Tree Requested
        note right of System
            Internal steps:
            1. Get Syntactic Tree (via Google API)
        end note
        
        System --> User: display syntactic tree analysis
    end
end
deactivate System

@enduml

@startuml TermStorage
hide footbox
skinparam sequenceMessageAlign center
title System Sequence Diagram: Terms Storage

actor User
participant "NoSense\nSystem" as System

User -> System: request to save terms
activate System
alt No sentence to save
    System --> User: display error "Please enter a sentence to analyze"
else Valid Input
    note right of System
      Internal steps:
      1. Save nouns, verbs, adjectives
    end note

    System --> User: confirm terms saved successfully
end
deactivate System

@enduml

@startuml SentenceGeneration
hide footbox
skinparam sequenceMessageAlign center
title System Sequence Diagram: Sentence Generation

actor User
participant "NoSense\nSystem" as System

User -> System: request to generate the sentence with the selected verbal tense
activate System

alt No Input Sentence Analyzed
    System --> User: display error "No input sentence has been analyzed yet"
else Input Sentence Available
    note right of System
      Internal steps:
      1. Generate template
      2. Select words
      3. Fill template
    end note
    System --> User: display generated sentence
end
deactivate System

@enduml

@startuml ToxicityAnalysis
hide footbox
skinparam sequenceMessageAlign center
title System Sequence Diagram: Toxicity Analysis

actor User
participant "NoSense\nSystem" as System

User -> System: request toxicity analysis
activate System

alt No Generated Sentence Analyzed
    System --> User: display error "No sentence has been generated yet to analyze"
else Valid Input
    note right of System
      Internal steps:
      1. Call Google API
      2. Parse Results
    end note

    alt Toxicity Found
        System --> User: display high toxicity warning
    else No Toxicity
        System --> User: display safe content confirmation
    end
end
deactivate System

@enduml