name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll bundler

      - name: Build the site
        run: |
          cd docs/pages
          jekyll build --source ../../docs --destination _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/pages/_site
